/// Enum representing all countries with ISO 3166-1 alpha-2 codes.
///
/// Each enum value contains country data (name, dial code, ISO code)
/// accessible directly without any async loading.
///
/// Example:
/// ```dart
/// final indonesia = CountryCode.ID;
/// print(indonesia.dialCode); // +62
/// print(indonesia.name); // Indonesia
/// print(indonesia.flagAssetPath); // packages/simple_phone_countries/assets/flags/id.svg
/// ```
enum CountryCode {
  AF(countryName: 'Afghanistan', dialCode: '+93'),
  AX(countryName: 'Aland Islands', dialCode: '+358'),
  AL(countryName: 'Albania', dialCode: '+355'),
  DZ(countryName: 'Algeria', dialCode: '+213'),
  AS(countryName: 'American Samoa', dialCode: '+1684'),
  AD(countryName: 'Andorra', dialCode: '+376'),
  AO(countryName: 'Angola', dialCode: '+244'),
  AI(countryName: 'Anguilla', dialCode: '+1264'),
  AQ(countryName: 'Antarctica', dialCode: '+672'),
  AG(countryName: 'Antigua and Barbuda', dialCode: '+1268'),
  AR(countryName: 'Argentina', dialCode: '+54'),
  AM(countryName: 'Armenia', dialCode: '+374'),
  AW(countryName: 'Aruba', dialCode: '+297'),
  AU(countryName: 'Australia', dialCode: '+61'),
  AT(countryName: 'Austria', dialCode: '+43'),
  AZ(countryName: 'Azerbaijan', dialCode: '+994'),
  BS(countryName: 'Bahamas', dialCode: '+1242'),
  BH(countryName: 'Bahrain', dialCode: '+973'),
  BD(countryName: 'Bangladesh', dialCode: '+880'),
  BB(countryName: 'Barbados', dialCode: '+1246'),
  BY(countryName: 'Belarus', dialCode: '+375'),
  BE(countryName: 'Belgium', dialCode: '+32'),
  BZ(countryName: 'Belize', dialCode: '+501'),
  BJ(countryName: 'Benin', dialCode: '+229'),
  BM(countryName: 'Bermuda', dialCode: '+1441'),
  BT(countryName: 'Bhutan', dialCode: '+975'),
  BO(countryName: 'Bolivia, Plurinational State of', dialCode: '+591'),
  BA(countryName: 'Bosnia and Herzegovina', dialCode: '+387'),
  BW(countryName: 'Botswana', dialCode: '+267'),
  BR(countryName: 'Brazil', dialCode: '+55'),
  IO(countryName: 'British Indian Ocean Territory', dialCode: '+246'),
  BN(countryName: 'Brunei Darussalam', dialCode: '+673'),
  BG(countryName: 'Bulgaria', dialCode: '+359'),
  BF(countryName: 'Burkina Faso', dialCode: '+226'),
  BI(countryName: 'Burundi', dialCode: '+257'),
  KH(countryName: 'Cambodia', dialCode: '+855'),
  CM(countryName: 'Cameroon', dialCode: '+237'),
  CA(countryName: 'Canada', dialCode: '+1'),
  CV(countryName: 'Cape Verde', dialCode: '+238'),
  KY(countryName: 'Cayman Islands', dialCode: '+345'),
  CF(countryName: 'Central African Republic', dialCode: '+236'),
  TD(countryName: 'Chad', dialCode: '+235'),
  CL(countryName: 'Chile', dialCode: '+56'),
  CN(countryName: 'China', dialCode: '+86'),
  CX(countryName: 'Christmas Island', dialCode: '+61'),
  CC(countryName: 'Cocos (Keeling) Islands', dialCode: '+61'),
  CO(countryName: 'Colombia', dialCode: '+57'),
  KM(countryName: 'Comoros', dialCode: '+269'),
  CG(countryName: 'Congo', dialCode: '+242'),
  CD(
      countryName: 'Congo, The Democratic Republic of the Congo',
      dialCode: '+243'),
  CK(countryName: 'Cook Islands', dialCode: '+682'),
  CR(countryName: 'Costa Rica', dialCode: '+506'),
  CI(countryName: "Cote d'Ivoire", dialCode: '+225'),
  HR(countryName: 'Croatia', dialCode: '+385'),
  CU(countryName: 'Cuba', dialCode: '+53'),
  CY(countryName: 'Cyprus', dialCode: '+357'),
  CZ(countryName: 'Czech Republic', dialCode: '+420'),
  DK(countryName: 'Denmark', dialCode: '+45'),
  DJ(countryName: 'Djibouti', dialCode: '+253'),
  DM(countryName: 'Dominica', dialCode: '+1767'),
  DO(countryName: 'Dominican Republic', dialCode: '+1849'),
  EC(countryName: 'Ecuador', dialCode: '+593'),
  EG(countryName: 'Egypt', dialCode: '+20'),
  SV(countryName: 'El Salvador', dialCode: '+503'),
  GQ(countryName: 'Equatorial Guinea', dialCode: '+240'),
  ER(countryName: 'Eritrea', dialCode: '+291'),
  EE(countryName: 'Estonia', dialCode: '+372'),
  ET(countryName: 'Ethiopia', dialCode: '+251'),
  FK(countryName: 'Falkland Islands (Malvinas)', dialCode: '+500'),
  FO(countryName: 'Faroe Islands', dialCode: '+298'),
  FJ(countryName: 'Fiji', dialCode: '+679'),
  FI(countryName: 'Finland', dialCode: '+358'),
  FR(countryName: 'France', dialCode: '+33'),
  GF(countryName: 'French Guiana', dialCode: '+594'),
  PF(countryName: 'French Polynesia', dialCode: '+689'),
  GA(countryName: 'Gabon', dialCode: '+241'),
  GM(countryName: 'Gambia', dialCode: '+220'),
  GE(countryName: 'Georgia', dialCode: '+995'),
  DE(countryName: 'Germany', dialCode: '+49'),
  GH(countryName: 'Ghana', dialCode: '+233'),
  GI(countryName: 'Gibraltar', dialCode: '+350'),
  GR(countryName: 'Greece', dialCode: '+30'),
  GL(countryName: 'Greenland', dialCode: '+299'),
  GD(countryName: 'Grenada', dialCode: '+1473'),
  GP(countryName: 'Guadeloupe', dialCode: '+590'),
  GU(countryName: 'Guam', dialCode: '+1671'),
  GT(countryName: 'Guatemala', dialCode: '+502'),
  GG(countryName: 'Guernsey', dialCode: '+44'),
  GN(countryName: 'Guinea', dialCode: '+224'),
  GW(countryName: 'Guinea-Bissau', dialCode: '+245'),
  GY(countryName: 'Guyana', dialCode: '+595'),
  HT(countryName: 'Haiti', dialCode: '+509'),
  VA(countryName: 'Holy See (Vatican City State)', dialCode: '+379'),
  HN(countryName: 'Honduras', dialCode: '+504'),
  HK(countryName: 'Hong Kong', dialCode: '+852'),
  HU(countryName: 'Hungary', dialCode: '+36'),
  IS(countryName: 'Iceland', dialCode: '+354'),
  IN(countryName: 'India', dialCode: '+91'),
  ID(countryName: 'Indonesia', dialCode: '+62'),
  IR(countryName: 'Iran, Islamic Republic of Persian Gulf', dialCode: '+98'),
  IQ(countryName: 'Iraq', dialCode: '+964'),
  IE(countryName: 'Ireland', dialCode: '+353'),
  IM(countryName: 'Isle of Man', dialCode: '+44'),
  IL(countryName: 'Israel', dialCode: '+972'),
  IT(countryName: 'Italy', dialCode: '+39'),
  JM(countryName: 'Jamaica', dialCode: '+1876'),
  JP(countryName: 'Japan', dialCode: '+81'),
  JE(countryName: 'Jersey', dialCode: '+44'),
  JO(countryName: 'Jordan', dialCode: '+962'),
  KZ(countryName: 'Kazakhstan', dialCode: '+77'),
  KE(countryName: 'Kenya', dialCode: '+254'),
  KI(countryName: 'Kiribati', dialCode: '+686'),
  KP(
      countryName: "Korea, Democratic People's Republic of Korea",
      dialCode: '+850'),
  KR(countryName: 'Korea, Republic of South Korea', dialCode: '+82'),
  KW(countryName: 'Kuwait', dialCode: '+965'),
  KG(countryName: 'Kyrgyzstan', dialCode: '+996'),
  LA(countryName: 'Laos', dialCode: '+856'),
  LV(countryName: 'Latvia', dialCode: '+371'),
  LB(countryName: 'Lebanon', dialCode: '+961'),
  LS(countryName: 'Lesotho', dialCode: '+266'),
  LR(countryName: 'Liberia', dialCode: '+231'),
  LY(countryName: 'Libyan Arab Jamahiriya', dialCode: '+218'),
  LI(countryName: 'Liechtenstein', dialCode: '+423'),
  LT(countryName: 'Lithuania', dialCode: '+370'),
  LU(countryName: 'Luxembourg', dialCode: '+352'),
  MO(countryName: 'Macao', dialCode: '+853'),
  MK(countryName: 'Macedonia', dialCode: '+389'),
  MG(countryName: 'Madagascar', dialCode: '+261'),
  MW(countryName: 'Malawi', dialCode: '+265'),
  MY(countryName: 'Malaysia', dialCode: '+60'),
  MV(countryName: 'Maldives', dialCode: '+960'),
  ML(countryName: 'Mali', dialCode: '+223'),
  MT(countryName: 'Malta', dialCode: '+356'),
  MH(countryName: 'Marshall Islands', dialCode: '+692'),
  MQ(countryName: 'Martinique', dialCode: '+596'),
  MR(countryName: 'Mauritania', dialCode: '+222'),
  MU(countryName: 'Mauritius', dialCode: '+230'),
  YT(countryName: 'Mayotte', dialCode: '+262'),
  MX(countryName: 'Mexico', dialCode: '+52'),
  FM(
      countryName: 'Micronesia, Federated States of Micronesia',
      dialCode: '+691'),
  MD(countryName: 'Moldova', dialCode: '+373'),
  MC(countryName: 'Monaco', dialCode: '+377'),
  MN(countryName: 'Mongolia', dialCode: '+976'),
  ME(countryName: 'Montenegro', dialCode: '+382'),
  MS(countryName: 'Montserrat', dialCode: '+1664'),
  MA(countryName: 'Morocco', dialCode: '+212'),
  MZ(countryName: 'Mozambique', dialCode: '+258'),
  MM(countryName: 'Myanmar', dialCode: '+95'),
  NA(countryName: 'Namibia', dialCode: '+264'),
  NR(countryName: 'Nauru', dialCode: '+674'),
  NP(countryName: 'Nepal', dialCode: '+977'),
  NL(countryName: 'Netherlands', dialCode: '+31'),
  NC(countryName: 'New Caledonia', dialCode: '+687'),
  NZ(countryName: 'New Zealand', dialCode: '+64'),
  NI(countryName: 'Nicaragua', dialCode: '+505'),
  NE(countryName: 'Niger', dialCode: '+227'),
  NG(countryName: 'Nigeria', dialCode: '+234'),
  NU(countryName: 'Niue', dialCode: '+683'),
  NF(countryName: 'Norfolk Island', dialCode: '+672'),
  MP(countryName: 'Northern Mariana Islands', dialCode: '+1670'),
  NO(countryName: 'Norway', dialCode: '+47'),
  OM(countryName: 'Oman', dialCode: '+968'),
  PK(countryName: 'Pakistan', dialCode: '+92'),
  PW(countryName: 'Palau', dialCode: '+680'),
  PS(countryName: 'Palestinian Territory, Occupied', dialCode: '+970'),
  PA(countryName: 'Panama', dialCode: '+507'),
  PG(countryName: 'Papua New Guinea', dialCode: '+675'),
  PY(countryName: 'Paraguay', dialCode: '+595'),
  PE(countryName: 'Peru', dialCode: '+51'),
  PH(countryName: 'Philippines', dialCode: '+63'),
  PN(countryName: 'Pitcairn', dialCode: '+872'),
  PL(countryName: 'Poland', dialCode: '+48'),
  PT(countryName: 'Portugal', dialCode: '+351'),
  PR(countryName: 'Puerto Rico', dialCode: '+1939'),
  QA(countryName: 'Qatar', dialCode: '+974'),
  RO(countryName: 'Romania', dialCode: '+40'),
  RU(countryName: 'Russia', dialCode: '+7'),
  RW(countryName: 'Rwanda', dialCode: '+250'),
  RE(countryName: 'Reunion', dialCode: '+262'),
  BL(countryName: 'Saint Barthelemy', dialCode: '+590'),
  SH(
      countryName: 'Saint Helena, Ascension and Tristan Da Cunha',
      dialCode: '+290'),
  KN(countryName: 'Saint Kitts and Nevis', dialCode: '+1869'),
  LC(countryName: 'Saint Lucia', dialCode: '+1758'),
  MF(countryName: 'Saint Martin', dialCode: '+590'),
  PM(countryName: 'Saint Pierre and Miquelon', dialCode: '+508'),
  VC(countryName: 'Saint Vincent and the Grenadines', dialCode: '+1784'),
  WS(countryName: 'Samoa', dialCode: '+685'),
  SM(countryName: 'San Marino', dialCode: '+378'),
  ST(countryName: 'Sao Tome and Principe', dialCode: '+239'),
  SA(countryName: 'Saudi Arabia', dialCode: '+966'),
  SN(countryName: 'Senegal', dialCode: '+221'),
  RS(countryName: 'Serbia', dialCode: '+381'),
  SC(countryName: 'Seychelles', dialCode: '+248'),
  SL(countryName: 'Sierra Leone', dialCode: '+232'),
  SG(countryName: 'Singapore', dialCode: '+65'),
  SK(countryName: 'Slovakia', dialCode: '+421'),
  SI(countryName: 'Slovenia', dialCode: '+386'),
  SB(countryName: 'Solomon Islands', dialCode: '+677'),
  SO(countryName: 'Somalia', dialCode: '+252'),
  ZA(countryName: 'South Africa', dialCode: '+27'),
  SS(countryName: 'South Sudan', dialCode: '+211'),
  GS(
      countryName: 'South Georgia and the South Sandwich Islands',
      dialCode: '+500'),
  ES(countryName: 'Spain', dialCode: '+34'),
  LK(countryName: 'Sri Lanka', dialCode: '+94'),
  SD(countryName: 'Sudan', dialCode: '+249'),
  SR(countryName: 'Suriname', dialCode: '+597'),
  SJ(countryName: 'Svalbard and Jan Mayen', dialCode: '+47'),
  SZ(countryName: 'Swaziland', dialCode: '+268'),
  SE(countryName: 'Sweden', dialCode: '+46'),
  CH(countryName: 'Switzerland', dialCode: '+41'),
  SY(countryName: 'Syrian Arab Republic', dialCode: '+963'),
  TW(countryName: 'Taiwan', dialCode: '+886'),
  TJ(countryName: 'Tajikistan', dialCode: '+992'),
  TZ(countryName: 'Tanzania, United Republic of Tanzania', dialCode: '+255'),
  TH(countryName: 'Thailand', dialCode: '+66'),
  TL(countryName: 'Timor-Leste', dialCode: '+670'),
  TG(countryName: 'Togo', dialCode: '+228'),
  TK(countryName: 'Tokelau', dialCode: '+690'),
  TO(countryName: 'Tonga', dialCode: '+676'),
  TT(countryName: 'Trinidad and Tobago', dialCode: '+1868'),
  TN(countryName: 'Tunisia', dialCode: '+216'),
  TR(countryName: 'Turkey', dialCode: '+90'),
  TM(countryName: 'Turkmenistan', dialCode: '+993'),
  TC(countryName: 'Turks and Caicos Islands', dialCode: '+1649'),
  TV(countryName: 'Tuvalu', dialCode: '+688'),
  UG(countryName: 'Uganda', dialCode: '+256'),
  UA(countryName: 'Ukraine', dialCode: '+380'),
  AE(countryName: 'United Arab Emirates', dialCode: '+971'),
  GB(countryName: 'United Kingdom', dialCode: '+44'),
  US(countryName: 'United States', dialCode: '+1'),
  UY(countryName: 'Uruguay', dialCode: '+598'),
  UZ(countryName: 'Uzbekistan', dialCode: '+998'),
  VU(countryName: 'Vanuatu', dialCode: '+678'),
  VE(
      countryName: 'Venezuela, Bolivarian Republic of Venezuela',
      dialCode: '+58'),
  VN(countryName: 'Vietnam', dialCode: '+84'),
  VG(countryName: 'Virgin Islands, British', dialCode: '+1284'),
  VI(countryName: 'Virgin Islands, U.S.', dialCode: '+1340'),
  WF(countryName: 'Wallis and Futuna', dialCode: '+681'),
  YE(countryName: 'Yemen', dialCode: '+967'),
  ZM(countryName: 'Zambia', dialCode: '+260'),
  ZW(countryName: 'Zimbabwe', dialCode: '+263');

  /// The full name of the country.
  final String countryName;

  /// The international dial code (e.g., "+1", "+62").
  final String dialCode;

  const CountryCode({required this.countryName, required this.dialCode});

  /// Returns the country name (alias for countryName).
  String get name => countryName;

  /// Returns the ISO 3166-1 alpha-2 country code (e.g., "US", "ID").
  /// This is derived from the enum name itself.
  String get code => toString().split('.').last;

  /// Returns the dial code without the "+" prefix.
  String get dialCodeWithoutPlus => dialCode.replaceAll('+', '').trim();

  /// Returns the lowercase country code.
  String get lowercaseCode => code.toLowerCase();

  /// Returns the flag asset path for this country.
  ///
  /// Use this with any SVG library like `flutter_svg`:
  /// ```dart
  /// SvgPicture.asset(CountryCode.ID.flagAssetPath)
  /// ```
  String get flagAssetPath =>
      'packages/simple_phone_countries/assets/flags/$lowercaseCode.svg';
}
